### ISSUE TITLE
Gerber files cleanup breaks Kitspace pages

### ISSUE THREAD

**Issue by kasbah** [eez-open/modular-psu#61]
Hey, 5093d6baf4961f45936e4f982cc5a77d7abef9c0 breaks the [Kitspace](https://kitspace.org) pages because we currently need the Gerber files in Git (not in zips). The pages are still up but won't update any more. The options to fix it:

1. Unzip the zip files 
2. Wait for https://github.com/kitspace/kitspace/pull/216 and Kitspace will plot the Gerbers for you from the KiCad files

Which option would you prefer?

**Comment by prasimix** [comment]
I'll unzip files, sorry that latest "clean up" actually made such a mess :)

**Comment by prasimix** [comment]
Fixed
