### ISSUE TITLE
Farnell and RS parts in 1-click-bom.csv are invalid

### ISSUE THREAD

**Issue by kasbah** [eez-open/modular-psu#65]
Just noticed there are a lot of parts numbers that are not correct for Farnell and RS for e.g. https://github.com/eez-open/modular-psu/blob/master/aux-ps/BOM/1-click-bom.csv.

Easiest thing to do would be to just remove those columns to avoid confusion.

**Comment by goran-mahovlic** [comment]
Will check and fix tomorrow

**Comment by goran-mahovlic** [comment]
I have recreated all BOMs so we can check after refresh on kitspace...

**Comment by kasbah** [comment]
Nice one, I can still spot one error in the [aux-ps one](https://github.com/eez-open/modular-psu/blob/master/aux-ps/BOM/1-click-bom.csv) (line 3, C0805C105K4RACTU for RS). It's also in [this one](https://github.com/eez-open/modular-psu/blob/master/dcm220/BOM/1-click-bom.csv#L8) and [here](https://github.com/eez-open/modular-psu/blob/master/dcp405/BOM/1-click-bom.csv#L16). 

Can you avoid using a `-` in the Digikey column or do you need it for something? It will cause errors when trying to add to cart I think.

**Comment by goran-mahovlic** [comment]
Tnx, please recheck now

**Comment by kasbah** [comment]
Looks better, [line 35](https://github.com/eez-open/modular-psu/blob/master/aux-ps/BOM/1-click-bom.csv#L35) is moved over by one I think?

**Comment by goran-mahovlic** [comment]
yes - now it is fixed.
I am using your 1 click BOM generator and autofill - and sometimes it adds problems

**Comment by kasbah** [comment]
Hmmm... it really shouldn't move things over like that! :scream: 

Are you also doing some manual editing that might have introduced that mistake? If you can reproduce the problems somehow, please do report. https://github.com/kitspace/bom-builder/issues

**Comment by goran-mahovlic** [comment]
Yes I am copy rows from here 

https://github.com/eez-open/modular-psu/blob/master/aux-ps/BOM/EEZ%20DIB%20AUX%20PS%20r3B3%20BOM.ods

And pasting to csv -
After that I do upload to generator -
Wait until it does search -
Click on Autofill -
Save

**Comment by kasbah** [comment]
Hmm, do you have a copy of the csv you pasted to from the ods, before you upload to the BOM Builder?

**Comment by goran-mahovlic** [comment]
will try to recreate and open issue if I catch error

https://github.com/kitspace/bom-builder/issues

**Comment by goran-mahovlic** [comment]
Reason of shift by one it is here:

![Shift](https://user-images.githubusercontent.com/4248736/75070173-01128b00-54f3-11ea-8a5b-9bfaf3ca5f73.png)

**Comment by kasbah** [comment]
Hmm, still if the CSV doesn't use a `;` seperator, that shouldn't be a problem. Even then, if it's quoted should be fine too. 

New BB3 pages are now deployed on kitspace.org btw. Unless you see any problems, I guess this can be closed: :tada:

**Comment by goran-mahovlic** [comment]
Yes, it is probably something that needs fix on BOM bilder ...

If you notice new issues with BB3 we will reopen this issue

**Comment by kasbah** [comment]
Hey, in [dcm220/BOM/1-click-bom.csv lines 55-56](https://github.com/eez-open/modular-psu/blob/master/dcm220/BOM/1-click-bom.csv#L55) the MPN columns seem to shift the distributor columns over.
