### ISSUE TITLE
why current and voltage control outputs are connected together

### ISSUE THREAD

**Issue by sfmth** [eez-open/modular-psu#77]
The output of current and voltage control poop are connected together and they go to the base of the main power transistors
How does a single wire control both current and voltage. The two control loops will just fight each other

**Comment by prasimix** [comment]
Take into account D12 and D13. In normal operation (i.e. most of the time) only one control loop has control over pass transistors. They are programmed separately with U_SET_OUT and I_SET signals that comes from DAC (IC16).

**Comment by sfmth** [comment]
Oh yeah right,
Thanks
