### ISSUE TITLE
MCU board: STM32F769IGT6 or STM32F769IIT6?

### ISSUE THREAD

**Issue by MartinD-CZ** [eez-open/modular-psu#89]
When going thru the files I noticed that the main page readme states that the MCU board uses the IGT6, while the /mcu readme states that IIT6 is used (this is also in BOM). They differ only in flash size AFAIK, so can either be used or only the IIT6 with it's larger flash?

(this is pretty minor, but still, it might confuse someone).
Otherwise, excellent project with great documentation, thanks a lot.

**Comment by prasimix** [comment]
Fixed
