### ISSUE TITLE
DCP405 BOM - R4 & R49 wrong footprint

### ISSUE THREAD

**Issue by MartinD-CZ** [eez-open/modular-psu#91]
These two resistors (item number 81 in the BOM) have their footprint specified as 1206, but their ordering numbers point to 2010 resistors. Also, their dissipation is specified at 0.75 W, which would be a lot for 1206. This applies to both the PDF and ODS versions of BOM.
So it's probably just typo and 2010 is supposed to be there.

**Comment by prasimix** [comment]
Fixed
